/** Catálogo de permisos del sistema */
export const PERMISSION_CODES = {
  DASHBOARD_VER: 'dashboard.ver',
  USUARIOS_VER: 'usuarios.ver',
  USUARIOS_CREAR: 'usuarios.crear',
  USUARIOS_EDITAR: 'usuarios.editar',
  USUARIOS_DESACTIVAR: 'usuarios.desactivar',
  PERMISOS_VER: 'permisos.ver',
  PERMISOS_ASIGNAR: 'permisos.asignar',
  CATEGORIAS_VER: 'categorias.ver',
  CATEGORIAS_CREAR: 'categorias.crear',
  CATEGORIAS_EDITAR: 'categorias.editar',
  CATEGORIAS_DESACTIVAR: 'categorias.desactivar',
  PRODUCTOS_VER: 'productos.ver',
  PRODUCTOS_CREAR: 'productos.crear',
  PRODUCTOS_EDITAR: 'productos.editar',
  PRODUCTOS_DESACTIVAR: 'productos.desactivar',
  CLIENTES_VER: 'clientes.ver',
  CLIENTES_CREAR: 'clientes.crear',
  CLIENTES_EDITAR: 'clientes.editar',
  CLIENTES_DESACTIVAR: 'clientes.desactivar',
  CUENTA_CORRIENTE_VER: 'cuenta_corriente.ver',
  CUENTA_CORRIENTE_COBRAR: 'cuenta_corriente.cobrar',
  CUENTA_CORRIENTE_AJUSTAR: 'cuenta_corriente.ajustar',
  INVENTARIO_VER: 'inventario.ver',
  INVENTARIO_MOVIMIENTO: 'inventario.movimiento',
  VENTAS_VER: 'ventas.ver',
  VENTAS_CREAR: 'ventas.crear',
  VENTAS_ANULAR: 'ventas.anular',
  CAJA_VER: 'caja.ver',
  CAJA_ABRIR: 'caja.abrir',
  CAJA_CERRAR: 'caja.cerrar',
  CAJA_MOVIMIENTO: 'caja.movimiento',
  COMPROBANTES_VER: 'comprobantes.ver',
  REPORTES_VER: 'reportes.ver',
  AUDITORIA_VER: 'auditoria.ver',
  METODOS_PAGO_VER: 'metodos_pago.ver',
  METODOS_PAGO_GESTIONAR: 'metodos_pago.gestionar',
};

export const ALL_PERMISSION_CODES = Object.values(PERMISSION_CODES);

export const DEFAULT_EMPLOYEE_PERMISSIONS = [PERMISSION_CODES.DASHBOARD_VER];

export const CONFIG_MENU_PERMISSIONS = [
  PERMISSION_CODES.USUARIOS_VER,
  PERMISSION_CODES.USUARIOS_CREAR,
  PERMISSION_CODES.USUARIOS_EDITAR,
  PERMISSION_CODES.USUARIOS_DESACTIVAR,
  PERMISSION_CODES.PERMISOS_VER,
  PERMISSION_CODES.PERMISOS_ASIGNAR,
  PERMISSION_CODES.METODOS_PAGO_GESTIONAR,
];

export const CATALOGO_MENU_PERMISSIONS = [
  PERMISSION_CODES.CATEGORIAS_VER,
  PERMISSION_CODES.CATEGORIAS_CREAR,
  PERMISSION_CODES.CATEGORIAS_EDITAR,
  PERMISSION_CODES.CATEGORIAS_DESACTIVAR,
  PERMISSION_CODES.PRODUCTOS_VER,
  PERMISSION_CODES.PRODUCTOS_CREAR,
  PERMISSION_CODES.PRODUCTOS_EDITAR,
  PERMISSION_CODES.PRODUCTOS_DESACTIVAR,
  PERMISSION_CODES.INVENTARIO_VER,
  PERMISSION_CODES.INVENTARIO_MOVIMIENTO,
];

export const VENTAS_MENU_PERMISSIONS = [
  PERMISSION_CODES.VENTAS_VER,
  PERMISSION_CODES.VENTAS_CREAR,
  PERMISSION_CODES.VENTAS_ANULAR,
];

export const CAJA_MENU_PERMISSIONS = [
  PERMISSION_CODES.CAJA_VER,
  PERMISSION_CODES.CAJA_ABRIR,
  PERMISSION_CODES.CAJA_CERRAR,
  PERMISSION_CODES.CAJA_MOVIMIENTO,
];

export const CLIENTES_MENU_PERMISSIONS = [
  PERMISSION_CODES.CLIENTES_VER,
  PERMISSION_CODES.CLIENTES_CREAR,
  PERMISSION_CODES.CLIENTES_EDITAR,
  PERMISSION_CODES.CLIENTES_DESACTIVAR,
  PERMISSION_CODES.CUENTA_CORRIENTE_VER,
  PERMISSION_CODES.CUENTA_CORRIENTE_COBRAR,
  PERMISSION_CODES.CUENTA_CORRIENTE_AJUSTAR,
];

/** @deprecated Use CLIENTES_MENU_PERMISSIONS */
export const COMERCIAL_MENU_PERMISSIONS = CLIENTES_MENU_PERMISSIONS;

export const FINANZAS_MENU_PERMISSIONS = [
  PERMISSION_CODES.COMPROBANTES_VER,
  PERMISSION_CODES.REPORTES_VER,
  PERMISSION_CODES.AUDITORIA_VER,
];

export const TIPOS_COMPROBANTE = ['ticket', 'factura', 'boleta'];

export const TIPOS_DOCUMENTO_CLIENTE = ['DNI', 'RUC', 'PASAPORTE', 'CF', 'OTRO'];

export const ROLES = {
  ADMIN: 'admin',
  EMPLEADO: 'empleado',
};

export const UNIDADES_MEDIDA = [
  'unidad',
  'kg',
  'g',
  'litro',
  'ml',
  'caja',
  'paquete',
];
